// Builds the Year 10 2.2 L4 plenary drill (y10-2-2-l4) and Do Now Extension drill (y10-2-2-l4-ext).
//   node tools/build_y10_2_2_l4_drills.mjs
// The plenary copies the check digit helpers (and their step-by-step walks) from Drills/data/y10-2-2-l4-calc.js, so
// the two methods are worked out the same way everywhere. Every card has a "Walk me through it" (`walk`): a
// different example worked step by step, never this card's answer. The Extension covers everything before this
// lesson (2.1 and 2.2 L1 to L3), with a why card for each error checking method (James, 2026-10-09).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const calc = fs.readFileSync(path.join(ROOT, 'Drills', 'data', 'y10-2-2-l4-calc.js'), 'utf8').replace(/\r\n/g, '\n');
const from = calc.indexOf('    // ---- shared check digit helpers');
const to = calc.indexOf('    // ---- end of shared helpers ----');
if (from < 0 || to < 0) throw new Error('helper block not found');
const helpers = calc.slice(from, to + '    // ---- end of shared helpers ----'.length);

const plenary = `// Year 10, 2.2 L4: Check Digits (Plenary)
// Loaded by Drills/index.html?drill=y10-2-2-l4
// Generated by tools/build_y10_2_2_l4_drills.mjs: edit that, then run it. What a check digit is for, the two methods
// from the 0478 papers (Method 1: add the digits, remainder after dividing by 10; Method 2: digit x position, MOD 11,
// 10 is X), accept or reject, and choosing between a check digit and the transmission checks. Every card has a
// "Walk me through it" on a different example.
DrillData.register("y10-2-2-l4", {
  title: "Year 10, 2.2 L4: Check Digits",
  subtitle: "Cambridge IGCSE Computer Science 0478",
  categories: [
    ["pl-why", "What a Check Digit Is For"],
    ["pl-calc", "Calculating a Check Digit"],
    ["pl-valid", "Accept or Reject"],
    ["pl-which", "Which Check?"]
  ],
  cards: (function () {
${helpers}
    var M1 = "Method 1: add the five digits, divide the total by 10, and the remainder is the check digit.";
    var M2 = "Method 2: multiply each digit by its position (the first digit is position 1), add the results, then MOD(Total, 11). A result of 10 is written as X.";
    function t(text) { return { text: text }; }
    function re(src) { return new RegExp(src, "i"); }
    return [
      // ================================================= What a check digit is for
      { id: "pl-01", category: "pl-why", prompt: "A check digit is used to find which kind of error?", answers: ["Errors in data entry"],
        keywords: [re("^(?!.*\\\\btransmi)(?=.*\\\\b(entry|entered|enter|typ\\\\w*|input\\\\w*|key\\\\w*|scan\\\\w*|read)\\\\b).*$")],
        distractors: ["Errors in data transmission", "Errors in storage", "Errors caused by a virus"],
        working: ["Think about where the mistake happens: when a person types or scans the number.", "Parity and checksums are for data sent from place to place. This one is different."],
        walk: [t("A similar question: a shop worker types a book number into the till and presses the wrong key."), t("Nothing has been sent anywhere yet. The mistake happened when the number was put in."), t("A check digit is worked out again from the digits that were typed. If it does not match, the number was put in wrongly.")] },
      { id: "pl-02", category: "pl-why", prompt: "Where in the number is the check digit?", answers: ["At the end"],
        keywords: [re("^\\\\s*(it\\\\s+is\\\\s+)?(at\\\\s+)?(the\\\\s+)?(end|last(\\\\s+digit)?|right\\\\s*(hand)?\\\\s*(end|side)?|final\\\\s+digit)\\\\s*\\\\.?$")],
        distractors: ["At the start", "In the middle", "In a separate file"],
        working: ["Look at a full code: the digits, then one more digit.", "The extra digit is added after the others."],
        walk: [t("A similar example: the number 4 1 8 2 3 has a check digit of 8."), t("The full code is written 4 1 8 2 3 8."), t("The digit that was calculated is the last one written.")] },
      { id: "pl-03", category: "pl-why", prompt: "Give one example of a number that has a check digit.", answers: ["An ISBN"],
        keywords: [re("^(?=.*\\\\b(isbn|book\\\\s*number|bar\\\\s*codes?|barcodes?|product\\\\s*code)\\\\b).*$")],
        distractors: ["A password", "An IP address", "A file name"],
        working: ["Think of a number on the back of a book.", "Or the striped code a shop scans at the till."],
        walk: [t("A similar question: name a number that is typed or scanned a lot, where one wrong digit would cause problems."), t("Books have a long number on the back, and shop items have a striped code that is scanned."), t("Both end in a check digit, so a mistyped or misread number is found.")] },
      { id: "pl-04", category: "pl-why", prompt: "A check digit does not match. Does the check digit correct the number?", answers: ["No"],
        keywords: [re("^\\\\s*(no|nope|it\\\\s+does\\\\s*n.?t|it\\\\s+does\\\\s+not|not)\\\\b(?!.*\\\\byes\\\\b)")],
        distractors: ["Yes"],
        working: ["The check digit only shows that something is wrong.", "Does it say which digit was wrong, or what it should be?"],
        walk: [t("A similar case: a parity check finds an odd number of 1s in a byte."), t("It knows there is an error, but not which bit changed or what it should be."), t("A check digit is the same: it finds the error. The number must be typed or scanned again.")] },
      { id: "pl-05", category: "pl-why", prompt: "Method 1 adds the digits. Which mistake can it NOT find?", answers: ["Two digits swapped"],
        keywords: [re("^(?=.*\\\\b(swap\\\\w*|transpos\\\\w*|switch\\\\w*|wrong\\\\s+order|order|reversed|swapped)\\\\b).*$")],
        distractors: ["One wrong digit", "A missing digit", "An extra digit"],
        working: ["Swap two digits and add them up again.", "Does the total change when the same digits are in a different order?"],
        walk: [t("A similar example: 3 5 2 1 4 adds up to 15."), t("Swap two digits: 5 3 2 1 4 still adds up to 15."), t("Adding does not care about order, so the check digit is the same and the swap is not found.")] },
      { id: "pl-06", category: "pl-why", prompt: "Why can Method 2 find two swapped digits when Method 1 cannot?", answers: ["Each digit is multiplied by its position, so swapping changes the total"],
        keywords: [re("^(?=.*\\\\b(position|place|weight\\\\w*|multipl\\\\w*|times)\\\\b).*$")],
        distractors: ["Method 2 uses more digits", "Method 2 divides by 11 so it is bigger", "Method 2 checks the number twice"],
        working: ["What does Method 2 do to each digit that Method 1 does not?", "If a digit moves to a new place, what is it multiplied by now?"],
        walk: [t("A similar example: digits 2 then 7 in positions 1 and 2 give 2 x 1 + 7 x 2 = 16."), t("Swapped: 7 then 2 give 7 x 1 + 2 x 2 = 11."), t("The total changed because each digit was multiplied by a different position.")] },
      // ================================================= Calculating
      { id: "pl-07", category: "pl-calc", randomize: function () {
          var s = digits(5), tt = sumTotal(s), r = tt % 10, w = otherNumber(s, sumCheck);
          return { prompt: M1 + "\\nNumber: " + s + "\\nWhat is the check digit?", answers: [String(r)], keywords: [numRe(String(r))],
            distractors: others(r, [(10 - r) % 10, tt, Math.floor(tt / 10), (r + 1) % 10, (r + 9) % 10]),
            walk: walkSum(w), working: ["Add the five digits, one at a time.", "Divide the total by ten. What is left over?"],
            note: tt + " ÷ 10 leaves " + r + ", so the check digit is " + r + "." };
        } },
      { id: "pl-08", category: "pl-calc", randomize: function () {
          var s = digits(5), tt = posTotal(s), a = posCheck(s), w = otherNumber(s, posCheck);
          return { prompt: M2 + "\\nNumber: " + s + "\\nWhat is the check digit?", answers: [a], keywords: [numRe(a)],
            distractors: others(a, [a === "X" ? "10" : tt, sumCheck(s), modX(revTotal(s)), String(tt % 10), "0"]),
            walk: walkPos(w, "check"), working: ["Multiply each digit by its position, then add the five results.", "Find the remainder after dividing the total by eleven."],
            note: "Total " + tt + ". MOD(" + tt + ", 11) = " + (tt % 11) + (a === "X" ? ", written as X." : ".") };
        } },
      { id: "pl-09", category: "pl-calc", randomize: function () {
          var s = digits(5), tt = posTotal(s), w = otherNumber(s, posTotal);
          return { prompt: M2 + "\\nNumber: " + s + "\\nStep 1: what is the total after multiplying each digit by its position?", answers: [String(tt)], keywords: [drillNumberRe(tt, "total")],
            distractors: others(tt, [revTotal(s), sumTotal(s), tt + 1, tt - 1, tt + 5]),
            walk: walkPos(w, "total"), working: ["The first digit is multiplied by 1, the second by 2, and so on.", "Add the five results."],
            note: "The total is " + tt + "." };
        } },
      // ================================================= Accept or reject
      { id: "pl-10", category: "pl-valid", randomize: function () {
          var s = digits(5), r = Number(sumCheck(s)), ok = Math.random() < 0.5, typed = ok ? r : (r + 1 + Math.floor(Math.random() * 9)) % 10;
          var w = otherNumber(s, sumCheck), wr = Number(sumCheck(w)), wtyped = ok ? (wr + 3) % 10 : wr;
          var ans = ok ? "Accept" : "Reject";
          return { prompt: M1 + "\\nThis code was typed in: " + s + typed + " (the last digit is the check digit).\\nAccept or reject it?", answers: [ans],
            keywords: [ok ? re("^\\\\s*(accept\\\\w*|valid|correct|ok|yes|it\\\\s+is\\\\s+(valid|correct))\\\\s*\\\\.?$") : re("^\\\\s*(reject\\\\w*|invalid|not\\\\s+valid|wrong|incorrect|no|error)\\\\s*\\\\.?$")],
            distractors: [ok ? "Reject" : "Accept", "Correct the check digit", "Send it again"],
            walk: walkSum(w, wtyped), working: ["Work out the check digit from the first five digits.", "Compare it with the last digit that was typed."],
            note: "The check digit should be " + r + ". The typed one is " + typed + ", so " + ans.toLowerCase() + "." };
        } },
      { id: "pl-11", category: "pl-valid", randomize: function () {
          var s = digits(5), a = posCheck(s), ok = Math.random() < 0.5, choices = ["0","1","2","3","4","5","6","7","8","9","X"].filter(function (c) { return c !== a; });
          var typed = ok ? a : choices[Math.floor(Math.random() * choices.length)];
          var w = otherNumber(s, posCheck), wa = posCheck(w), wtyped = ok ? (wa === "0" ? "1" : "0") : wa;
          var ans = ok ? "Accept" : "Reject";
          return { prompt: M2 + "\\nThis code was typed in: " + s + typed + " (the last character is the check digit).\\nAccept or reject it?", answers: [ans],
            keywords: [ok ? re("^\\\\s*(accept\\\\w*|valid|correct|ok|yes|it\\\\s+is\\\\s+(valid|correct))\\\\s*\\\\.?$") : re("^\\\\s*(reject\\\\w*|invalid|not\\\\s+valid|wrong|incorrect|no|error)\\\\s*\\\\.?$")],
            distractors: [ok ? "Reject" : "Accept", "Correct the check digit", "Send it again"],
            walk: walkPos(w, wtyped), working: ["Work out the check digit from the first five digits with Method 2.", "Compare it with the last character typed."],
            note: "The check digit should be " + a + ". The typed one is " + typed + ", so " + ans.toLowerCase() + "." };
        } },
      // ================================================= Which check?
      { id: "pl-12", category: "pl-which", randomize: function () {
          var v = drillPick([["A librarian types a book number into the computer.", "Check digit"], ["A cashier scans the striped code on a packet of rice.", "Check digit"],
            ["A file is sent from a laptop to a printer down a cable. Data entry or transmission?", "Transmission"], ["A photo is sent over the internet in packets. Data entry or transmission?", "Transmission"]]);
          var entry = v[1] === "Check digit";
          var ok = entry ? re("^(?=.*\\\\bcheck\\\\s*digit).*$") : re("^\\\\s*(a\\\\s+)?(data\\\\s+)?transmi\\\\w*(\\\\s+(error|check)s?)?\\\\s*\\\\.?$");
          return { prompt: v[0] + (entry ? "\\nWhich check is best here?" : ""), answers: [v[1]], keywords: [ok],
            distractors: entry ? ["Parity check", "Checksum", "Echo check"] : ["Data entry", "Both", "Neither"],
            working: ["Is the number being typed or scanned in, or is data being sent somewhere?", "Data entry: check digit. Data sent: parity, checksum, echo check or ARQ."],
            walk: [t("A similar case: a nurse types a patient's ID number into a computer."), t("The data is being entered, not sent, so the mistake would happen at the keyboard."), t("Checks for data entry differ from checks for data sent down a cable or over a network. Choose by where the mistake can happen.")],
            note: v[1] === "Check digit" ? "Data entry, so a check digit." : "Data is being sent, so a transmission check such as " + v[1].toLowerCase() + " (any transmission check is accepted)." };
        } },
      { id: "pl-13", category: "pl-which", prompt: "Why is a check digit no help for data sent down a cable?", answers: ["It only checks the number when it is entered, not changes during transmission"],
        keywords: [re("^(?=.*\\\\b(enter\\\\w*|entry|typ\\\\w*|input\\\\w*|scan\\\\w*)\\\\b).*$")],
        distractors: ["Cables cannot carry digits", "It is too slow for cables", "Cables already correct every error"],
        working: ["When is a check digit worked out and compared?", "Bits that change later, on the way, need a check made when the data arrives."],
        walk: [t("A similar question: why is a parity check no help when someone types the wrong ISBN?"), t("The wrong number would get the right parity bit, because the parity is worked out after the mistake."), t("Each check finds the errors made at its own stage: entry or transmission.")] }
    ];
  })()
});
`;
fs.writeFileSync(path.join(ROOT, 'Drills', 'data', 'y10-2-2-l4.js'), plenary);
console.log('plenary written');
