// Builds the four Year 8 homework drills set after the Term 1 Test (James, 2026-10-08), one per group of students
// with the same gaps in the test (results export, anonymous, 13 students):
//   y8-hw-search  Searching and Counting      secure students: the search that resets Found, counting, finding bugs
//   y8-hw-loops   WHILE Loops and Arrays       every one of them got WHILE wrong; loops over arrays weak
//   y8-hw-trace   Tracing and Comparisons      > and >=, FOR loops, tracing one line at a time
//   y8-hw-read    Reading Programs             assignment, one IF, flowchart shapes, array positions
// Named by topic, never by group. Every card kind is in tools/y8_homework_kit.js; each card has a "Walk me
// through it" (card.walk, Drills/engine.js renderWalk) on a similar program, worked one line at a time.
//   node tools/build_y8_homework.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const kit = fs.readFileSync(path.join(ROOT, 'tools', 'y8_homework_kit.js'), 'utf8').replace(/\r\n/g, '\n');

const DRILLS = [
  { id: 'y8-hw-search', title: 'Year 8 Homework: Searching and Counting', subtitle: 'Searches, counting with > and >=, and finding logic errors',
    cats: [['hw-search', 'Linear Search'], ['hw-count', 'Counting and Adding'], ['hw-bugs', 'Logic Errors'], ['hw-while', 'WHILE Loops']],
    cards: [['searchReset', 'hw-search'], ['searchLine', 'hw-search'], ['searchOut', 'hw-search'], ['arrCount', 'hw-count'], ['arrPart', 'hw-count'],
      ['bugOut', 'hw-bugs'], ['bugLine', 'hw-bugs'], ['whileCount', 'hw-while'], ['swap', 'hw-bugs']] },
  { id: 'y8-hw-loops', title: 'Year 8 Homework: WHILE Loops and Arrays', subtitle: 'WHILE loops, and FOR loops that go through an array',
    cats: [['hw-while', 'WHILE Loops'], ['hw-arrloop', 'Loops over an Array'], ['hw-for', 'FOR Loops']],
    cards: [['whileDown', 'hw-while'], ['whileCount', 'hw-while'], ['arrPart', 'hw-arrloop'], ['arrTable', 'hw-arrloop'], ['arrCount', 'hw-arrloop'],
      ['arrTotalLine', 'hw-arrloop'], ['forInside', 'hw-for'], ['forOut', 'hw-for'], ['swap', 'hw-for']] },
  { id: 'y8-hw-trace', title: 'Year 8 Homework: Tracing and Comparisons', subtitle: 'Following a program one line at a time, > and >=, FOR loops',
    cats: [['hw-compare', '> and >='], ['hw-seq', 'One Line at a Time'], ['hw-for', 'FOR Loops']],
    cards: [['countPass', 'hw-compare'], ['fixIf', 'hw-compare'], ['changeIf', 'hw-seq'], ['twoIf', 'hw-seq'], ['swap', 'hw-seq'],
      ['forOut', 'hw-for'], ['forTimes', 'hw-for'], ['forTable', 'hw-for']] },
  { id: 'y8-hw-read', title: 'Year 8 Homework: Reading Programs', subtitle: 'Variables, one IF, flowchart shapes and arrays, one step at a time',
    cats: [['hw-var', 'Variables'], ['hw-if', 'One IF'], ['hw-loop', 'A First Loop'], ['hw-shape', 'Flowchart Shapes'], ['hw-array', 'Arrays']],
    cards: [['chain', 'hw-var', true], ['chain', 'hw-var', false], ['ifElse', 'hw-if'], ['symbol', 'hw-shape'], ['arrValue', 'hw-array'], ['arrIndex', 'hw-array'],
      ['forOut', 'hw-loop', true]] }
];

for (const d of DRILLS) {
  const calls = d.cards.map(([kind, cat, opt]) => `K.${kind}(${JSON.stringify(cat)}${opt === undefined ? '' : ', ' + JSON.stringify(opt)})`);
  const body = `// ${d.title}
// Loaded by Drills/index.html?drill=${d.id}
// Generated by tools/build_y8_homework.mjs from tools/y8_homework_kit.js: edit those, then run the builder.
// Homework after the Year 8 Term 1 Test for the students whose results showed these gaps. Every card has a
// "Walk me through it" in Learn mode's help: a similar program, worked one line at a time.
DrillData.register(${JSON.stringify(d.id)}, {
  title: ${JSON.stringify(d.title)},
  subtitle: ${JSON.stringify(d.subtitle)},
  categories: ${JSON.stringify(d.cats)},
  cards: (function () {
${kit}
    return [
      ${calls.join(',\n      ')}
    ];
  })()
});
`;
  if (/[–—]/.test(body)) throw new Error('dash in ' + d.id);
  fs.writeFileSync(path.join(ROOT, 'Drills', 'data', d.id + '.js'), body);
  console.log(d.id + ': ' + d.cards.length + ' cards');
}
